/**
 * Write the local Kong image build context
 */

import * as fs from 'fs';
import * as path from 'path';
import { logger } from '../logger';
import {
  KONG_GENERATED_FILE_HEADER,
  KONG_LOCAL_BUILD_CONTEXT,
  KONG_PLUGINS_DIR,
} from '../../constants';
import { writeKongBuildContext } from './write-kong-build-context';

/**
 * Writes the Dockerfile and plugins into infrastructure/kong, the context
 * docker-compose builds the gateway image from. The config is not baked in:
 * compose mounts kong.yml and sets the local ports and Admin API.
 *
 * A hand-written Dockerfile (no generated header) is overwritten with a
 * warning: custom build steps move to kong-plugins/.
 */
export function writeLocalKongBuildContext(rootDir: string): void {
  logger.info(
    `Writing Kong image build context (${KONG_LOCAL_BUILD_CONTEXT})...`,
  );
  const contextDir = path.join(rootDir, KONG_LOCAL_BUILD_CONTEXT);
  const dockerfilePath = path.join(contextDir, 'Dockerfile');

  if (
    fs.existsSync(dockerfilePath) &&
    !fs
      .readFileSync(dockerfilePath, 'utf-8')
      .startsWith(KONG_GENERATED_FILE_HEADER)
  ) {
    logger.warn(
      `${KONG_LOCAL_BUILD_CONTEXT}/Dockerfile is now generated by tsdevstack and is being overwritten.`,
    );
    logger.warn(
      `   Move custom Kong plugins into ${KONG_PLUGINS_DIR}/ at the project root (one folder per plugin); other custom build steps are not carried over.`,
    );
  }

  const kongPlugins = writeKongBuildContext({
    projectRoot: rootDir,
    contextDir,
  });
  logger.success(
    `Generated ${KONG_LOCAL_BUILD_CONTEXT}/Dockerfile (KONG_PLUGINS=${kongPlugins.join(',')})`,
  );
  logger.info(
    `   Custom plugins: one folder per plugin in ${KONG_PLUGINS_DIR}/ at the project root`,
  );
  logger.newline();
}
