/**
 * Generate .env files for backend NestJS services
 *
 * Backend services get their secrets from SecretsService at runtime,
 * but Prisma Studio needs DATABASE_URL in a local .env file.
 */

import * as path from 'path';
import { logger } from '../logger';
import { LOCAL_SECRETS_FILE, BACKEND_TYPES } from '../../constants';
import { findProjectRoot } from '../paths';
import { getServicePath } from '../paths/get-service-path';
import { writeTextFile, readJsonFile } from '../fs';
import type { FrameworkConfig } from '../config';
import type { SecretsFile } from './types';

/**
 * Generate .env file for a single backend service
 *
 * Only includes DATABASE_URL for Prisma Studio/Prisma CLI tools.
 * The running service gets all its environment variables from SecretsService.
 *
 * @param serviceName - Name of the backend service
 * @param serviceSecrets - Secrets for this service from .secrets.local.json
 * @param rootDir - Project root directory
 */
function generateServiceEnvFile(
  serviceName: string,
  serviceSecrets: Record<string, unknown>,
  rootDir: string
): void {
  // Check if service has DATABASE_URL
  if (!serviceSecrets.DATABASE_URL) {
    // Skip services without DATABASE_URL
    return;
  }

  // Build env file content
  const header = `################################################################################
# ⚠️  AUTO-GENERATED BY TSDEVSTACK - DO NOT EDIT ⚠️
################################################################################
# Generated from: ${LOCAL_SECRETS_FILE}
# Generated at: ${new Date().toISOString()}
#
# This file is used by Prisma Studio and Prisma CLI tools only.
# The running service gets its environment variables from SecretsService.
#
# This file is automatically created and OVERWRITTEN when you run:
#   npx tsdevstack generate-secrets
#
# To modify DATABASE_URL:
#   1. Edit .secrets.user.json
#   2. Run: npx tsdevstack generate-secrets
#   3. This file will be regenerated automatically
#
# ⚠️  DO NOT EDIT THIS FILE DIRECTLY - ALL CHANGES WILL BE LOST! ⚠️
################################################################################

`;

  const envLines: string[] = [header];

  // Only include DATABASE_URL
  if (typeof serviceSecrets.DATABASE_URL === 'string') {
    envLines.push(`DATABASE_URL="${serviceSecrets.DATABASE_URL}"`);
  }

  // Write to .env in service directory
  const servicePath = getServicePath(serviceName, rootDir);
  const envPath = path.join(servicePath, '.env');
  writeTextFile(envPath, envLines.join('\n') + '\n');

  logger.success(`Generated .env for ${serviceName} (DATABASE_URL only)`);
}

/**
 * Generate .env files for all backend NestJS services
 * Reads service sections from .secrets.local.json and creates individual .env files
 *
 * @param config - Framework configuration
 * @param rootDir - Project root directory (defaults to findProjectRoot())
 */
export function generateBackendEnvFiles(
  config: FrameworkConfig,
  rootDir: string = findProjectRoot()
): void {
  // Load structured secrets from .secrets.local.json
  const secretsPath = path.join(rootDir, LOCAL_SECRETS_FILE);
  const secretsFile = readJsonFile<SecretsFile>(secretsPath);

  // Count backend services for logging
  let backendCount = 0;

  // Process each service
  for (const service of config.services) {
    // Only process backend services
    if (!(BACKEND_TYPES as readonly string[]).includes(service.type)) {
      continue;
    }

    backendCount++;

    // Get this service's secrets section
    const serviceSection = secretsFile[service.name];

    if (!serviceSection || typeof serviceSection !== 'object') {
      logger.warn(`No secrets found for ${service.name} in ${LOCAL_SECRETS_FILE}`);
      continue;
    }

    // Generate .env file for this service (only if it has DATABASE_URL)
    generateServiceEnvFile(service.name, serviceSection as Record<string, unknown>, rootDir);
  }

  if (backendCount === 0) {
    logger.info('No backend services found - skipping .env generation');
  }
}