/**
 * Generate .env file from secrets for Docker/Kong
 */

import * as path from 'path';
import { logger } from '../logger';
import { LOCAL_SECRETS_FILE, USER_SECRETS_FILE } from '../../constants';
import { findProjectRoot } from '../paths';
import { writeTextFile } from '../fs';
import { loadLocalSecretsFile } from './load-local-secrets';

/**
 * Generate .env file from .secrets.local.json
 * This file is used by docker-compose.yml and kong.yaml for variable substitution
 *
 * IMPORTANT: Only includes framework-wide shared secrets from the "secrets" key.
 * Service-specific secrets (DATABASE_URL, PORT, API_KEY, etc.) are excluded
 * as they are loaded by each service via SecretsService based on service name.
 *
 * @param rootDir - Project root directory (defaults to findProjectRoot())
 */
export function generateEnvFile(rootDir: string = findProjectRoot()): void {
  // Load the full secrets file structure
  const secretsFile = loadLocalSecretsFile(rootDir);

  // Build secrets object with only framework-wide shared secrets
  const secrets: Record<string, string> = {};

  // 1. Include only the framework-wide shared secrets from top-level "secrets" key
  const sharedSecrets = secretsFile.secrets || {};
  for (const [key, value] of Object.entries(sharedSecrets)) {
    if (typeof value === 'string') {
      secrets[key] = value;
    } else if (value && typeof value === 'object' && !Array.isArray(value)) {
      // Handle nested objects like REDIS
      for (const [nestedKey, nestedValue] of Object.entries(value)) {
        if (typeof nestedValue === 'string') {
          secrets[nestedKey] = nestedValue;
        }
      }
    }
  }

  // 2. Extract DB user/password for docker-compose.yml (needed for container env vars)
  // These are extracted from service DATABASE_URLs but named *_DB_USER, *_DB_PASSWORD
  // IMPORTANT: Matches docker-compose generator pattern (removes -service suffix)
  for (const [serviceName, serviceConfig] of Object.entries(secretsFile)) {
    if (serviceName === 'secrets' || serviceName.startsWith('$')) continue;

    if (serviceConfig && typeof serviceConfig === 'object' && 'DATABASE_URL' in serviceConfig) {
      const dbUrl = serviceConfig.DATABASE_URL as string;
      if (typeof dbUrl === 'string') {
        // Extract user and password from postgresql://user:password@host:port/database
        const match = dbUrl.match(/postgresql:\/\/([^:]+):([^@]+)@/);
        if (match) {
          // Remove -service suffix to match docker-compose generator
          // auth-service → auth → AUTH_DB_USER
          const dbName = serviceName.replace(/-service$/, '').replace(/-/g, '_').toUpperCase();
          secrets[`${dbName}_DB_USER`] = match[1];
          // URL-decode the password (it's URL-encoded in DATABASE_URL but Docker needs raw value)
          secrets[`${dbName}_DB_PASSWORD`] = decodeURIComponent(match[2]);
        }
      }
    }
  }

  // Build env file content
  const header = `################################################################################
# ⚠️  AUTO-GENERATED BY TSDEVSTACK - DO NOT EDIT ⚠️
################################################################################
# Generated from: ${LOCAL_SECRETS_FILE}
# Generated at: ${new Date().toISOString()}
#
# This file is automatically created and OVERWRITTEN when you run:
#   npx tsdevstack generate-secrets
#
# To add or modify secrets:
#   1. Edit ${USER_SECRETS_FILE} (for your custom secrets)
#   2. Run: npx tsdevstack generate-secrets
#   3. This file will be regenerated automatically
#
# ⚠️  DO NOT EDIT THIS FILE DIRECTLY - ALL CHANGES WILL BE LOST! ⚠️
################################################################################

`;

  const envLines: string[] = [header];

  // Convert secrets to KEY=VALUE format
  for (const [key, value] of Object.entries(secrets)) {
    // Skip NODE_ENV - it should not be in .env as it interferes with Next.js builds
    // NestJS apps will read NODE_ENV from their own environment, not from .env
    if (key === 'NODE_ENV') {
      continue;
    }

    // Skip JWT keys - they are multiline PEM format and only needed by NestJS apps
    // NestJS apps load these from .secrets.local.json via SecretsService
    // Docker Compose doesn't need these keys
    if (
      key === 'JWT_PRIVATE_KEY_CURRENT' ||
      key === 'JWT_PUBLIC_KEY_CURRENT' ||
      key === 'JWT_KEY_ID_CURRENT' ||
      key === 'JWT_PRIVATE_KEY_PREVIOUS' ||
      key === 'JWT_PUBLIC_KEY_PREVIOUS' ||
      key === 'JWT_KEY_ID_PREVIOUS'
    ) {
      continue;
    }

    // Escape special characters in values
    const escapedValue = value.toString().replace(/\$/g, '\\$').replace(/"/g, '\\"');
    envLines.push(`${key}=${escapedValue}`);
  }

  // Write to .env in project root
  const envPath = path.join(rootDir, '.env');
  writeTextFile(envPath, envLines.join('\n') + '\n');

  logger.success('Generated .env for Docker/Kong');
}